//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSoft.HDServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ContollerWebService.com/", ConfigurationName="HDServiceReference.ControllerSoap")]
    public interface ControllerSoap {
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 ReadCardDataResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ReadCardData", ReplyAction="*")]
        QSoft.HDServiceReference.ReadCardDataResponse ReadCardData(QSoft.HDServiceReference.ReadCardDataRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 content 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PrintSlip", ReplyAction="*")]
        QSoft.HDServiceReference.PrintSlipResponse PrintSlip(QSoft.HDServiceReference.PrintSlipRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 contentCN 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PlaySpeakerSound", ReplyAction="*")]
        QSoft.HDServiceReference.PlaySpeakerSoundResponse PlaySpeakerSound(QSoft.HDServiceReference.PlaySpeakerSoundRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ShowScreenMSG", ReplyAction="*")]
        QSoft.HDServiceReference.ShowScreenMSGResponse ShowScreenMSG(QSoft.HDServiceReference.ShowScreenMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PlayEvaluateSound", ReplyAction="*")]
        QSoft.HDServiceReference.PlayEvaluateSoundResponse PlayEvaluateSound(QSoft.HDServiceReference.PlayEvaluateSoundRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ShowEvaluateMSG", ReplyAction="*")]
        QSoft.HDServiceReference.ShowEvaluateMSGResponse ShowEvaluateMSG(QSoft.HDServiceReference.ShowEvaluateMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ShowCallerMSG", ReplyAction="*")]
        QSoft.HDServiceReference.ShowCallerMSGResponse ShowCallerMSG(QSoft.HDServiceReference.ShowCallerMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PlayCallerSound", ReplyAction="*")]
        QSoft.HDServiceReference.PlayCallerSoundResponse PlayCallerSound(QSoft.HDServiceReference.PlayCallerSoundRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/GetDeviceStatus", ReplyAction="*")]
        QSoft.HDServiceReference.GetDeviceStatusResponse GetDeviceStatus(QSoft.HDServiceReference.GetDeviceStatusRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/GetDeviceMSG", ReplyAction="*")]
        QSoft.HDServiceReference.GetDeviceMSGResponse GetDeviceMSG(QSoft.HDServiceReference.GetDeviceMSGRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCardDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCardData", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ReadCardDataRequestBody Body;
        
        public ReadCardDataRequest() {
        }
        
        public ReadCardDataRequest(QSoft.HDServiceReference.ReadCardDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ReadCardDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int track;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int timeout;
        
        public ReadCardDataRequestBody() {
        }
        
        public ReadCardDataRequestBody(int devType, int track, int timeout) {
            this.devType = devType;
            this.track = track;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCardDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCardDataResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ReadCardDataResponseBody Body;
        
        public ReadCardDataResponse() {
        }
        
        public ReadCardDataResponse(QSoft.HDServiceReference.ReadCardDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ReadCardDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadCardDataResult;
        
        public ReadCardDataResponseBody() {
        }
        
        public ReadCardDataResponseBody(string ReadCardDataResult) {
            this.ReadCardDataResult = ReadCardDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintSlip", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PrintSlipRequestBody Body;
        
        public PrintSlipRequest() {
        }
        
        public PrintSlipRequest(QSoft.HDServiceReference.PrintSlipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PrintSlipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int timeout;
        
        public PrintSlipRequestBody() {
        }
        
        public PrintSlipRequestBody(string content, int timeout) {
            this.content = content;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintSlipResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PrintSlipResponseBody Body;
        
        public PrintSlipResponse() {
        }
        
        public PrintSlipResponse(QSoft.HDServiceReference.PrintSlipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PrintSlipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintSlipResult;
        
        public PrintSlipResponseBody() {
        }
        
        public PrintSlipResponseBody(string PrintSlipResult) {
            this.PrintSlipResult = PrintSlipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaySpeakerSoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaySpeakerSound", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PlaySpeakerSoundRequestBody Body;
        
        public PlaySpeakerSoundRequest() {
        }
        
        public PlaySpeakerSoundRequest(QSoft.HDServiceReference.PlaySpeakerSoundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlaySpeakerSoundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentCN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contentEN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string playSequence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int volume;
        
        public PlaySpeakerSoundRequestBody() {
        }
        
        public PlaySpeakerSoundRequestBody(int playType, string contentCN, string contentEN, string playSequence, int volume) {
            this.playType = playType;
            this.contentCN = contentCN;
            this.contentEN = contentEN;
            this.playSequence = playSequence;
            this.volume = volume;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaySpeakerSoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaySpeakerSoundResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PlaySpeakerSoundResponseBody Body;
        
        public PlaySpeakerSoundResponse() {
        }
        
        public PlaySpeakerSoundResponse(QSoft.HDServiceReference.PlaySpeakerSoundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlaySpeakerSoundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlaySpeakerSoundResult;
        
        public PlaySpeakerSoundResponseBody() {
        }
        
        public PlaySpeakerSoundResponseBody(string PlaySpeakerSoundResult) {
            this.PlaySpeakerSoundResult = PlaySpeakerSoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowScreenMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowScreenMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ShowScreenMSGRequestBody Body;
        
        public ShowScreenMSGRequest() {
        }
        
        public ShowScreenMSGRequest(QSoft.HDServiceReference.ShowScreenMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowScreenMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int showType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string billNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string windowNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string msg;
        
        public ShowScreenMSGRequestBody() {
        }
        
        public ShowScreenMSGRequestBody(int devType, int showType, string devAddr, int width, int height, string billNum, string windowNum, string msg) {
            this.devType = devType;
            this.showType = showType;
            this.devAddr = devAddr;
            this.width = width;
            this.height = height;
            this.billNum = billNum;
            this.windowNum = windowNum;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowScreenMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowScreenMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ShowScreenMSGResponseBody Body;
        
        public ShowScreenMSGResponse() {
        }
        
        public ShowScreenMSGResponse(QSoft.HDServiceReference.ShowScreenMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowScreenMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowScreenMSGResult;
        
        public ShowScreenMSGResponseBody() {
        }
        
        public ShowScreenMSGResponseBody(string ShowScreenMSGResult) {
            this.ShowScreenMSGResult = ShowScreenMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayEvaluateSoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayEvaluateSound", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PlayEvaluateSoundRequestBody Body;
        
        public PlayEvaluateSoundRequest() {
        }
        
        public PlayEvaluateSoundRequest(QSoft.HDServiceReference.PlayEvaluateSoundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayEvaluateSoundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        public PlayEvaluateSoundRequestBody() {
        }
        
        public PlayEvaluateSoundRequestBody(int playType, string devAddr) {
            this.playType = playType;
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayEvaluateSoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayEvaluateSoundResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PlayEvaluateSoundResponseBody Body;
        
        public PlayEvaluateSoundResponse() {
        }
        
        public PlayEvaluateSoundResponse(QSoft.HDServiceReference.PlayEvaluateSoundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayEvaluateSoundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlayEvaluateSoundResult;
        
        public PlayEvaluateSoundResponseBody() {
        }
        
        public PlayEvaluateSoundResponseBody(string PlayEvaluateSoundResult) {
            this.PlayEvaluateSoundResult = PlayEvaluateSoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowEvaluateMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowEvaluateMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ShowEvaluateMSGRequestBody Body;
        
        public ShowEvaluateMSGRequest() {
        }
        
        public ShowEvaluateMSGRequest(QSoft.HDServiceReference.ShowEvaluateMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowEvaluateMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int star;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string devAddr;
        
        public ShowEvaluateMSGRequestBody() {
        }
        
        public ShowEvaluateMSGRequestBody(int staffID, int star, string devAddr) {
            this.staffID = staffID;
            this.star = star;
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowEvaluateMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowEvaluateMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ShowEvaluateMSGResponseBody Body;
        
        public ShowEvaluateMSGResponse() {
        }
        
        public ShowEvaluateMSGResponse(QSoft.HDServiceReference.ShowEvaluateMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowEvaluateMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowEvaluateMSGResult;
        
        public ShowEvaluateMSGResponseBody() {
        }
        
        public ShowEvaluateMSGResponseBody(string ShowEvaluateMSGResult) {
            this.ShowEvaluateMSGResult = ShowEvaluateMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowCallerMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowCallerMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ShowCallerMSGRequestBody Body;
        
        public ShowCallerMSGRequest() {
        }
        
        public ShowCallerMSGRequest(QSoft.HDServiceReference.ShowCallerMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowCallerMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int showType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string customerNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int leftCustomerCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string customerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int login;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int logout;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int pauseService;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int resumeService;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string msg;
        
        public ShowCallerMSGRequestBody() {
        }
        
        public ShowCallerMSGRequestBody(int showType, string devAddr, string modelType, string customerNum, int leftCustomerCount, string customerName, int login, int logout, int pauseService, int resumeService, string msg) {
            this.showType = showType;
            this.devAddr = devAddr;
            this.modelType = modelType;
            this.customerNum = customerNum;
            this.leftCustomerCount = leftCustomerCount;
            this.customerName = customerName;
            this.login = login;
            this.logout = logout;
            this.pauseService = pauseService;
            this.resumeService = resumeService;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowCallerMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowCallerMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.ShowCallerMSGResponseBody Body;
        
        public ShowCallerMSGResponse() {
        }
        
        public ShowCallerMSGResponse(QSoft.HDServiceReference.ShowCallerMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowCallerMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowCallerMSGResult;
        
        public ShowCallerMSGResponseBody() {
        }
        
        public ShowCallerMSGResponseBody(string ShowCallerMSGResult) {
            this.ShowCallerMSGResult = ShowCallerMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayCallerSoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayCallerSound", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PlayCallerSoundRequestBody Body;
        
        public PlayCallerSoundRequest() {
        }
        
        public PlayCallerSoundRequest(QSoft.HDServiceReference.PlayCallerSoundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayCallerSoundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devAddr;
        
        public PlayCallerSoundRequestBody() {
        }
        
        public PlayCallerSoundRequestBody(string devAddr) {
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayCallerSoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayCallerSoundResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.PlayCallerSoundResponseBody Body;
        
        public PlayCallerSoundResponse() {
        }
        
        public PlayCallerSoundResponse(QSoft.HDServiceReference.PlayCallerSoundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayCallerSoundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlayCallerSoundResult;
        
        public PlayCallerSoundResponseBody() {
        }
        
        public PlayCallerSoundResponseBody(string PlayCallerSoundResult) {
            this.PlayCallerSoundResult = PlayCallerSoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceStatus", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.GetDeviceStatusRequestBody Body;
        
        public GetDeviceStatusRequest() {
        }
        
        public GetDeviceStatusRequest(QSoft.HDServiceReference.GetDeviceStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int timeout;
        
        public GetDeviceStatusRequestBody() {
        }
        
        public GetDeviceStatusRequestBody(int devType, string devAddr, int width, int height, int timeout) {
            this.devType = devType;
            this.devAddr = devAddr;
            this.width = width;
            this.height = height;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceStatusResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.GetDeviceStatusResponseBody Body;
        
        public GetDeviceStatusResponse() {
        }
        
        public GetDeviceStatusResponse(QSoft.HDServiceReference.GetDeviceStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceStatusResult;
        
        public GetDeviceStatusResponseBody() {
        }
        
        public GetDeviceStatusResponseBody(string GetDeviceStatusResult) {
            this.GetDeviceStatusResult = GetDeviceStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.GetDeviceMSGRequestBody Body;
        
        public GetDeviceMSGRequest() {
        }
        
        public GetDeviceMSGRequest(QSoft.HDServiceReference.GetDeviceMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int timeout;
        
        public GetDeviceMSGRequestBody() {
        }
        
        public GetDeviceMSGRequestBody(int devType, string devAddr, int timeout) {
            this.devType = devType;
            this.devAddr = devAddr;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QSoft.HDServiceReference.GetDeviceMSGResponseBody Body;
        
        public GetDeviceMSGResponse() {
        }
        
        public GetDeviceMSGResponse(QSoft.HDServiceReference.GetDeviceMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceMSGResult;
        
        public GetDeviceMSGResponseBody() {
        }
        
        public GetDeviceMSGResponseBody(string GetDeviceMSGResult) {
            this.GetDeviceMSGResult = GetDeviceMSGResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControllerSoapChannel : QSoft.HDServiceReference.ControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControllerSoapClient : System.ServiceModel.ClientBase<QSoft.HDServiceReference.ControllerSoap>, QSoft.HDServiceReference.ControllerSoap {
        
        public ControllerSoapClient() {
        }
        
        public ControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.ReadCardDataResponse QSoft.HDServiceReference.ControllerSoap.ReadCardData(QSoft.HDServiceReference.ReadCardDataRequest request) {
            return base.Channel.ReadCardData(request);
        }
        
        public string ReadCardData(int devType, int track, int timeout) {
            QSoft.HDServiceReference.ReadCardDataRequest inValue = new QSoft.HDServiceReference.ReadCardDataRequest();
            inValue.Body = new QSoft.HDServiceReference.ReadCardDataRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.track = track;
            inValue.Body.timeout = timeout;
            QSoft.HDServiceReference.ReadCardDataResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).ReadCardData(inValue);
            return retVal.Body.ReadCardDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.PrintSlipResponse QSoft.HDServiceReference.ControllerSoap.PrintSlip(QSoft.HDServiceReference.PrintSlipRequest request) {
            return base.Channel.PrintSlip(request);
        }
        
        public string PrintSlip(string content, int timeout) {
            QSoft.HDServiceReference.PrintSlipRequest inValue = new QSoft.HDServiceReference.PrintSlipRequest();
            inValue.Body = new QSoft.HDServiceReference.PrintSlipRequestBody();
            inValue.Body.content = content;
            inValue.Body.timeout = timeout;
            QSoft.HDServiceReference.PrintSlipResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).PrintSlip(inValue);
            return retVal.Body.PrintSlipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.PlaySpeakerSoundResponse QSoft.HDServiceReference.ControllerSoap.PlaySpeakerSound(QSoft.HDServiceReference.PlaySpeakerSoundRequest request) {
            return base.Channel.PlaySpeakerSound(request);
        }
        
        public string PlaySpeakerSound(int playType, string contentCN, string contentEN, string playSequence, int volume) {
            QSoft.HDServiceReference.PlaySpeakerSoundRequest inValue = new QSoft.HDServiceReference.PlaySpeakerSoundRequest();
            inValue.Body = new QSoft.HDServiceReference.PlaySpeakerSoundRequestBody();
            inValue.Body.playType = playType;
            inValue.Body.contentCN = contentCN;
            inValue.Body.contentEN = contentEN;
            inValue.Body.playSequence = playSequence;
            inValue.Body.volume = volume;
            QSoft.HDServiceReference.PlaySpeakerSoundResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).PlaySpeakerSound(inValue);
            return retVal.Body.PlaySpeakerSoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.ShowScreenMSGResponse QSoft.HDServiceReference.ControllerSoap.ShowScreenMSG(QSoft.HDServiceReference.ShowScreenMSGRequest request) {
            return base.Channel.ShowScreenMSG(request);
        }
        
        public string ShowScreenMSG(int devType, int showType, string devAddr, int width, int height, string billNum, string windowNum, string msg) {
            QSoft.HDServiceReference.ShowScreenMSGRequest inValue = new QSoft.HDServiceReference.ShowScreenMSGRequest();
            inValue.Body = new QSoft.HDServiceReference.ShowScreenMSGRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.showType = showType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.billNum = billNum;
            inValue.Body.windowNum = windowNum;
            inValue.Body.msg = msg;
            QSoft.HDServiceReference.ShowScreenMSGResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).ShowScreenMSG(inValue);
            return retVal.Body.ShowScreenMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.PlayEvaluateSoundResponse QSoft.HDServiceReference.ControllerSoap.PlayEvaluateSound(QSoft.HDServiceReference.PlayEvaluateSoundRequest request) {
            return base.Channel.PlayEvaluateSound(request);
        }
        
        public string PlayEvaluateSound(int playType, string devAddr) {
            QSoft.HDServiceReference.PlayEvaluateSoundRequest inValue = new QSoft.HDServiceReference.PlayEvaluateSoundRequest();
            inValue.Body = new QSoft.HDServiceReference.PlayEvaluateSoundRequestBody();
            inValue.Body.playType = playType;
            inValue.Body.devAddr = devAddr;
            QSoft.HDServiceReference.PlayEvaluateSoundResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).PlayEvaluateSound(inValue);
            return retVal.Body.PlayEvaluateSoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.ShowEvaluateMSGResponse QSoft.HDServiceReference.ControllerSoap.ShowEvaluateMSG(QSoft.HDServiceReference.ShowEvaluateMSGRequest request) {
            return base.Channel.ShowEvaluateMSG(request);
        }
        
        public string ShowEvaluateMSG(int staffID, int star, string devAddr) {
            QSoft.HDServiceReference.ShowEvaluateMSGRequest inValue = new QSoft.HDServiceReference.ShowEvaluateMSGRequest();
            inValue.Body = new QSoft.HDServiceReference.ShowEvaluateMSGRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.star = star;
            inValue.Body.devAddr = devAddr;
            QSoft.HDServiceReference.ShowEvaluateMSGResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).ShowEvaluateMSG(inValue);
            return retVal.Body.ShowEvaluateMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.ShowCallerMSGResponse QSoft.HDServiceReference.ControllerSoap.ShowCallerMSG(QSoft.HDServiceReference.ShowCallerMSGRequest request) {
            return base.Channel.ShowCallerMSG(request);
        }
        
        public string ShowCallerMSG(int showType, string devAddr, string modelType, string customerNum, int leftCustomerCount, string customerName, int login, int logout, int pauseService, int resumeService, string msg) {
            QSoft.HDServiceReference.ShowCallerMSGRequest inValue = new QSoft.HDServiceReference.ShowCallerMSGRequest();
            inValue.Body = new QSoft.HDServiceReference.ShowCallerMSGRequestBody();
            inValue.Body.showType = showType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.modelType = modelType;
            inValue.Body.customerNum = customerNum;
            inValue.Body.leftCustomerCount = leftCustomerCount;
            inValue.Body.customerName = customerName;
            inValue.Body.login = login;
            inValue.Body.logout = logout;
            inValue.Body.pauseService = pauseService;
            inValue.Body.resumeService = resumeService;
            inValue.Body.msg = msg;
            QSoft.HDServiceReference.ShowCallerMSGResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).ShowCallerMSG(inValue);
            return retVal.Body.ShowCallerMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.PlayCallerSoundResponse QSoft.HDServiceReference.ControllerSoap.PlayCallerSound(QSoft.HDServiceReference.PlayCallerSoundRequest request) {
            return base.Channel.PlayCallerSound(request);
        }
        
        public string PlayCallerSound(string devAddr) {
            QSoft.HDServiceReference.PlayCallerSoundRequest inValue = new QSoft.HDServiceReference.PlayCallerSoundRequest();
            inValue.Body = new QSoft.HDServiceReference.PlayCallerSoundRequestBody();
            inValue.Body.devAddr = devAddr;
            QSoft.HDServiceReference.PlayCallerSoundResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).PlayCallerSound(inValue);
            return retVal.Body.PlayCallerSoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.GetDeviceStatusResponse QSoft.HDServiceReference.ControllerSoap.GetDeviceStatus(QSoft.HDServiceReference.GetDeviceStatusRequest request) {
            return base.Channel.GetDeviceStatus(request);
        }
        
        public string GetDeviceStatus(int devType, string devAddr, int width, int height, int timeout) {
            QSoft.HDServiceReference.GetDeviceStatusRequest inValue = new QSoft.HDServiceReference.GetDeviceStatusRequest();
            inValue.Body = new QSoft.HDServiceReference.GetDeviceStatusRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.timeout = timeout;
            QSoft.HDServiceReference.GetDeviceStatusResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).GetDeviceStatus(inValue);
            return retVal.Body.GetDeviceStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QSoft.HDServiceReference.GetDeviceMSGResponse QSoft.HDServiceReference.ControllerSoap.GetDeviceMSG(QSoft.HDServiceReference.GetDeviceMSGRequest request) {
            return base.Channel.GetDeviceMSG(request);
        }
        
        public string GetDeviceMSG(int devType, string devAddr, int timeout) {
            QSoft.HDServiceReference.GetDeviceMSGRequest inValue = new QSoft.HDServiceReference.GetDeviceMSGRequest();
            inValue.Body = new QSoft.HDServiceReference.GetDeviceMSGRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.timeout = timeout;
            QSoft.HDServiceReference.GetDeviceMSGResponse retVal = ((QSoft.HDServiceReference.ControllerSoap)(this)).GetDeviceMSG(inValue);
            return retVal.Body.GetDeviceMSGResult;
        }
    }
}
