//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QClient.HD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ContollerWebService.com/", ConfigurationName="HD.ControllerSoap")]
    public interface ControllerSoap {
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 ReadCardDataResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ReadCardData", ReplyAction="*")]
        QClient.HD.ReadCardDataResponse ReadCardData(QClient.HD.ReadCardDataRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 content 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PrintSlip", ReplyAction="*")]
        QClient.HD.PrintSlipResponse PrintSlip(QClient.HD.PrintSlipRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 contentCN 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PlaySpeakerSound", ReplyAction="*")]
        QClient.HD.PlaySpeakerSoundResponse PlaySpeakerSound(QClient.HD.PlaySpeakerSoundRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ShowScreenMSG", ReplyAction="*")]
        QClient.HD.ShowScreenMSGResponse ShowScreenMSG(QClient.HD.ShowScreenMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PlayEvaluateSound", ReplyAction="*")]
        QClient.HD.PlayEvaluateSoundResponse PlayEvaluateSound(QClient.HD.PlayEvaluateSoundRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ShowEvaluateMSG", ReplyAction="*")]
        QClient.HD.ShowEvaluateMSGResponse ShowEvaluateMSG(QClient.HD.ShowEvaluateMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/ShowCallerMSG", ReplyAction="*")]
        QClient.HD.ShowCallerMSGResponse ShowCallerMSG(QClient.HD.ShowCallerMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/PlayCallerSound", ReplyAction="*")]
        QClient.HD.PlayCallerSoundResponse PlayCallerSound(QClient.HD.PlayCallerSoundRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/GetDeviceStatus", ReplyAction="*")]
        QClient.HD.GetDeviceStatusResponse GetDeviceStatus(QClient.HD.GetDeviceStatusRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/GetDeviceMSG", ReplyAction="*")]
        QClient.HD.GetDeviceMSGResponse GetDeviceMSG(QClient.HD.GetDeviceMSGRequest request);
        
        // CODEGEN: 命名空间 http://ContollerWebService.com/ 的元素名称 devAddr 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ContollerWebService.com/InitDevice", ReplyAction="*")]
        QClient.HD.InitDeviceResponse InitDevice(QClient.HD.InitDeviceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCardDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCardData", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ReadCardDataRequestBody Body;
        
        public ReadCardDataRequest() {
        }
        
        public ReadCardDataRequest(QClient.HD.ReadCardDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ReadCardDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int track;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int timeout;
        
        public ReadCardDataRequestBody() {
        }
        
        public ReadCardDataRequestBody(int devType, int track, int timeout) {
            this.devType = devType;
            this.track = track;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadCardDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadCardDataResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ReadCardDataResponseBody Body;
        
        public ReadCardDataResponse() {
        }
        
        public ReadCardDataResponse(QClient.HD.ReadCardDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ReadCardDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadCardDataResult;
        
        public ReadCardDataResponseBody() {
        }
        
        public ReadCardDataResponseBody(string ReadCardDataResult) {
            this.ReadCardDataResult = ReadCardDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintSlip", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PrintSlipRequestBody Body;
        
        public PrintSlipRequest() {
        }
        
        public PrintSlipRequest(QClient.HD.PrintSlipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PrintSlipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int timeout;
        
        public PrintSlipRequestBody() {
        }
        
        public PrintSlipRequestBody(string content, int timeout) {
            this.content = content;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintSlipResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PrintSlipResponseBody Body;
        
        public PrintSlipResponse() {
        }
        
        public PrintSlipResponse(QClient.HD.PrintSlipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PrintSlipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintSlipResult;
        
        public PrintSlipResponseBody() {
        }
        
        public PrintSlipResponseBody(string PrintSlipResult) {
            this.PrintSlipResult = PrintSlipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaySpeakerSoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaySpeakerSound", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PlaySpeakerSoundRequestBody Body;
        
        public PlaySpeakerSoundRequest() {
        }
        
        public PlaySpeakerSoundRequest(QClient.HD.PlaySpeakerSoundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlaySpeakerSoundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentCN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contentEN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string playSequence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int volume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string customerNO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string windowNO;
        
        public PlaySpeakerSoundRequestBody() {
        }
        
        public PlaySpeakerSoundRequestBody(int playType, string contentCN, string contentEN, string playSequence, int volume, string customerNO, string windowNO) {
            this.playType = playType;
            this.contentCN = contentCN;
            this.contentEN = contentEN;
            this.playSequence = playSequence;
            this.volume = volume;
            this.customerNO = customerNO;
            this.windowNO = windowNO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaySpeakerSoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaySpeakerSoundResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PlaySpeakerSoundResponseBody Body;
        
        public PlaySpeakerSoundResponse() {
        }
        
        public PlaySpeakerSoundResponse(QClient.HD.PlaySpeakerSoundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlaySpeakerSoundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlaySpeakerSoundResult;
        
        public PlaySpeakerSoundResponseBody() {
        }
        
        public PlaySpeakerSoundResponseBody(string PlaySpeakerSoundResult) {
            this.PlaySpeakerSoundResult = PlaySpeakerSoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowScreenMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowScreenMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ShowScreenMSGRequestBody Body;
        
        public ShowScreenMSGRequest() {
        }
        
        public ShowScreenMSGRequest(QClient.HD.ShowScreenMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowScreenMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int showType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string billNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string windowNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string msg;
        
        public ShowScreenMSGRequestBody() {
        }
        
        public ShowScreenMSGRequestBody(int devType, int showType, string devAddr, int width, int height, string billNum, string windowNum, string msg) {
            this.devType = devType;
            this.showType = showType;
            this.devAddr = devAddr;
            this.width = width;
            this.height = height;
            this.billNum = billNum;
            this.windowNum = windowNum;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowScreenMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowScreenMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ShowScreenMSGResponseBody Body;
        
        public ShowScreenMSGResponse() {
        }
        
        public ShowScreenMSGResponse(QClient.HD.ShowScreenMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowScreenMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowScreenMSGResult;
        
        public ShowScreenMSGResponseBody() {
        }
        
        public ShowScreenMSGResponseBody(string ShowScreenMSGResult) {
            this.ShowScreenMSGResult = ShowScreenMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayEvaluateSoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayEvaluateSound", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PlayEvaluateSoundRequestBody Body;
        
        public PlayEvaluateSoundRequest() {
        }
        
        public PlayEvaluateSoundRequest(QClient.HD.PlayEvaluateSoundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayEvaluateSoundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        public PlayEvaluateSoundRequestBody() {
        }
        
        public PlayEvaluateSoundRequestBody(int playType, string devAddr) {
            this.playType = playType;
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayEvaluateSoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayEvaluateSoundResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PlayEvaluateSoundResponseBody Body;
        
        public PlayEvaluateSoundResponse() {
        }
        
        public PlayEvaluateSoundResponse(QClient.HD.PlayEvaluateSoundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayEvaluateSoundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlayEvaluateSoundResult;
        
        public PlayEvaluateSoundResponseBody() {
        }
        
        public PlayEvaluateSoundResponseBody(string PlayEvaluateSoundResult) {
            this.PlayEvaluateSoundResult = PlayEvaluateSoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowEvaluateMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowEvaluateMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ShowEvaluateMSGRequestBody Body;
        
        public ShowEvaluateMSGRequest() {
        }
        
        public ShowEvaluateMSGRequest(QClient.HD.ShowEvaluateMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowEvaluateMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int star;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string devAddr;
        
        public ShowEvaluateMSGRequestBody() {
        }
        
        public ShowEvaluateMSGRequestBody(int staffID, int star, string devAddr) {
            this.staffID = staffID;
            this.star = star;
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowEvaluateMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowEvaluateMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ShowEvaluateMSGResponseBody Body;
        
        public ShowEvaluateMSGResponse() {
        }
        
        public ShowEvaluateMSGResponse(QClient.HD.ShowEvaluateMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowEvaluateMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowEvaluateMSGResult;
        
        public ShowEvaluateMSGResponseBody() {
        }
        
        public ShowEvaluateMSGResponseBody(string ShowEvaluateMSGResult) {
            this.ShowEvaluateMSGResult = ShowEvaluateMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowCallerMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowCallerMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ShowCallerMSGRequestBody Body;
        
        public ShowCallerMSGRequest() {
        }
        
        public ShowCallerMSGRequest(QClient.HD.ShowCallerMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowCallerMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int showType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string customerNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int leftCustomerCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string customerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int login;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int logout;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int pauseService;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int resumeService;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string msg;
        
        public ShowCallerMSGRequestBody() {
        }
        
        public ShowCallerMSGRequestBody(int showType, string devAddr, string modelType, string customerNum, int leftCustomerCount, string customerName, int login, int logout, int pauseService, int resumeService, string msg) {
            this.showType = showType;
            this.devAddr = devAddr;
            this.modelType = modelType;
            this.customerNum = customerNum;
            this.leftCustomerCount = leftCustomerCount;
            this.customerName = customerName;
            this.login = login;
            this.logout = logout;
            this.pauseService = pauseService;
            this.resumeService = resumeService;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowCallerMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowCallerMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.ShowCallerMSGResponseBody Body;
        
        public ShowCallerMSGResponse() {
        }
        
        public ShowCallerMSGResponse(QClient.HD.ShowCallerMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class ShowCallerMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowCallerMSGResult;
        
        public ShowCallerMSGResponseBody() {
        }
        
        public ShowCallerMSGResponseBody(string ShowCallerMSGResult) {
            this.ShowCallerMSGResult = ShowCallerMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayCallerSoundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayCallerSound", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PlayCallerSoundRequestBody Body;
        
        public PlayCallerSoundRequest() {
        }
        
        public PlayCallerSoundRequest(QClient.HD.PlayCallerSoundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayCallerSoundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devAddr;
        
        public PlayCallerSoundRequestBody() {
        }
        
        public PlayCallerSoundRequestBody(string devAddr) {
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlayCallerSoundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlayCallerSoundResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.PlayCallerSoundResponseBody Body;
        
        public PlayCallerSoundResponse() {
        }
        
        public PlayCallerSoundResponse(QClient.HD.PlayCallerSoundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class PlayCallerSoundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PlayCallerSoundResult;
        
        public PlayCallerSoundResponseBody() {
        }
        
        public PlayCallerSoundResponseBody(string PlayCallerSoundResult) {
            this.PlayCallerSoundResult = PlayCallerSoundResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceStatus", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.GetDeviceStatusRequestBody Body;
        
        public GetDeviceStatusRequest() {
        }
        
        public GetDeviceStatusRequest(QClient.HD.GetDeviceStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int timeout;
        
        public GetDeviceStatusRequestBody() {
        }
        
        public GetDeviceStatusRequestBody(int devType, string devAddr, int width, int height, int timeout) {
            this.devType = devType;
            this.devAddr = devAddr;
            this.width = width;
            this.height = height;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceStatusResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.GetDeviceStatusResponseBody Body;
        
        public GetDeviceStatusResponse() {
        }
        
        public GetDeviceStatusResponse(QClient.HD.GetDeviceStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceStatusResult;
        
        public GetDeviceStatusResponseBody() {
        }
        
        public GetDeviceStatusResponseBody(string GetDeviceStatusResult) {
            this.GetDeviceStatusResult = GetDeviceStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceMSGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceMSG", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.GetDeviceMSGRequestBody Body;
        
        public GetDeviceMSGRequest() {
        }
        
        public GetDeviceMSGRequest(QClient.HD.GetDeviceMSGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceMSGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int timeout;
        
        public GetDeviceMSGRequestBody() {
        }
        
        public GetDeviceMSGRequestBody(int devType, string devAddr, int timeout) {
            this.devType = devType;
            this.devAddr = devAddr;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceMSGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceMSGResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.GetDeviceMSGResponseBody Body;
        
        public GetDeviceMSGResponse() {
        }
        
        public GetDeviceMSGResponse(QClient.HD.GetDeviceMSGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class GetDeviceMSGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceMSGResult;
        
        public GetDeviceMSGResponseBody() {
        }
        
        public GetDeviceMSGResponseBody(string GetDeviceMSGResult) {
            this.GetDeviceMSGResult = GetDeviceMSGResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitDevice", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.InitDeviceRequestBody Body;
        
        public InitDeviceRequest() {
        }
        
        public InitDeviceRequest(QClient.HD.InitDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class InitDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int devType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string devAddr;
        
        public InitDeviceRequestBody() {
        }
        
        public InitDeviceRequestBody(int devType, string devAddr) {
            this.devType = devType;
            this.devAddr = devAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitDeviceResponse", Namespace="http://ContollerWebService.com/", Order=0)]
        public QClient.HD.InitDeviceResponseBody Body;
        
        public InitDeviceResponse() {
        }
        
        public InitDeviceResponse(QClient.HD.InitDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ContollerWebService.com/")]
    public partial class InitDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InitDeviceResult;
        
        public InitDeviceResponseBody() {
        }
        
        public InitDeviceResponseBody(string InitDeviceResult) {
            this.InitDeviceResult = InitDeviceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControllerSoapChannel : QClient.HD.ControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControllerSoapClient : System.ServiceModel.ClientBase<QClient.HD.ControllerSoap>, QClient.HD.ControllerSoap {
        
        public ControllerSoapClient() {
        }
        
        public ControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.ReadCardDataResponse QClient.HD.ControllerSoap.ReadCardData(QClient.HD.ReadCardDataRequest request) {
            return base.Channel.ReadCardData(request);
        }
        
        public string ReadCardData(int devType, int track, int timeout) {
            QClient.HD.ReadCardDataRequest inValue = new QClient.HD.ReadCardDataRequest();
            inValue.Body = new QClient.HD.ReadCardDataRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.track = track;
            inValue.Body.timeout = timeout;
            QClient.HD.ReadCardDataResponse retVal = ((QClient.HD.ControllerSoap)(this)).ReadCardData(inValue);
            return retVal.Body.ReadCardDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.PrintSlipResponse QClient.HD.ControllerSoap.PrintSlip(QClient.HD.PrintSlipRequest request) {
            return base.Channel.PrintSlip(request);
        }
        
        public string PrintSlip(string content, int timeout) {
            QClient.HD.PrintSlipRequest inValue = new QClient.HD.PrintSlipRequest();
            inValue.Body = new QClient.HD.PrintSlipRequestBody();
            inValue.Body.content = content;
            inValue.Body.timeout = timeout;
            QClient.HD.PrintSlipResponse retVal = ((QClient.HD.ControllerSoap)(this)).PrintSlip(inValue);
            return retVal.Body.PrintSlipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.PlaySpeakerSoundResponse QClient.HD.ControllerSoap.PlaySpeakerSound(QClient.HD.PlaySpeakerSoundRequest request) {
            return base.Channel.PlaySpeakerSound(request);
        }
        
        public string PlaySpeakerSound(int playType, string contentCN, string contentEN, string playSequence, int volume, string customerNO, string windowNO) {
            QClient.HD.PlaySpeakerSoundRequest inValue = new QClient.HD.PlaySpeakerSoundRequest();
            inValue.Body = new QClient.HD.PlaySpeakerSoundRequestBody();
            inValue.Body.playType = playType;
            inValue.Body.contentCN = contentCN;
            inValue.Body.contentEN = contentEN;
            inValue.Body.playSequence = playSequence;
            inValue.Body.volume = volume;
            inValue.Body.customerNO = customerNO;
            inValue.Body.windowNO = windowNO;
            QClient.HD.PlaySpeakerSoundResponse retVal = ((QClient.HD.ControllerSoap)(this)).PlaySpeakerSound(inValue);
            return retVal.Body.PlaySpeakerSoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.ShowScreenMSGResponse QClient.HD.ControllerSoap.ShowScreenMSG(QClient.HD.ShowScreenMSGRequest request) {
            return base.Channel.ShowScreenMSG(request);
        }
        
        public string ShowScreenMSG(int devType, int showType, string devAddr, int width, int height, string billNum, string windowNum, string msg) {
            QClient.HD.ShowScreenMSGRequest inValue = new QClient.HD.ShowScreenMSGRequest();
            inValue.Body = new QClient.HD.ShowScreenMSGRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.showType = showType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.billNum = billNum;
            inValue.Body.windowNum = windowNum;
            inValue.Body.msg = msg;
            QClient.HD.ShowScreenMSGResponse retVal = ((QClient.HD.ControllerSoap)(this)).ShowScreenMSG(inValue);
            return retVal.Body.ShowScreenMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.PlayEvaluateSoundResponse QClient.HD.ControllerSoap.PlayEvaluateSound(QClient.HD.PlayEvaluateSoundRequest request) {
            return base.Channel.PlayEvaluateSound(request);
        }
        
        public string PlayEvaluateSound(int playType, string devAddr) {
            QClient.HD.PlayEvaluateSoundRequest inValue = new QClient.HD.PlayEvaluateSoundRequest();
            inValue.Body = new QClient.HD.PlayEvaluateSoundRequestBody();
            inValue.Body.playType = playType;
            inValue.Body.devAddr = devAddr;
            QClient.HD.PlayEvaluateSoundResponse retVal = ((QClient.HD.ControllerSoap)(this)).PlayEvaluateSound(inValue);
            return retVal.Body.PlayEvaluateSoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.ShowEvaluateMSGResponse QClient.HD.ControllerSoap.ShowEvaluateMSG(QClient.HD.ShowEvaluateMSGRequest request) {
            return base.Channel.ShowEvaluateMSG(request);
        }
        
        public string ShowEvaluateMSG(int staffID, int star, string devAddr) {
            QClient.HD.ShowEvaluateMSGRequest inValue = new QClient.HD.ShowEvaluateMSGRequest();
            inValue.Body = new QClient.HD.ShowEvaluateMSGRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.star = star;
            inValue.Body.devAddr = devAddr;
            QClient.HD.ShowEvaluateMSGResponse retVal = ((QClient.HD.ControllerSoap)(this)).ShowEvaluateMSG(inValue);
            return retVal.Body.ShowEvaluateMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.ShowCallerMSGResponse QClient.HD.ControllerSoap.ShowCallerMSG(QClient.HD.ShowCallerMSGRequest request) {
            return base.Channel.ShowCallerMSG(request);
        }
        
        public string ShowCallerMSG(int showType, string devAddr, string modelType, string customerNum, int leftCustomerCount, string customerName, int login, int logout, int pauseService, int resumeService, string msg) {
            QClient.HD.ShowCallerMSGRequest inValue = new QClient.HD.ShowCallerMSGRequest();
            inValue.Body = new QClient.HD.ShowCallerMSGRequestBody();
            inValue.Body.showType = showType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.modelType = modelType;
            inValue.Body.customerNum = customerNum;
            inValue.Body.leftCustomerCount = leftCustomerCount;
            inValue.Body.customerName = customerName;
            inValue.Body.login = login;
            inValue.Body.logout = logout;
            inValue.Body.pauseService = pauseService;
            inValue.Body.resumeService = resumeService;
            inValue.Body.msg = msg;
            QClient.HD.ShowCallerMSGResponse retVal = ((QClient.HD.ControllerSoap)(this)).ShowCallerMSG(inValue);
            return retVal.Body.ShowCallerMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.PlayCallerSoundResponse QClient.HD.ControllerSoap.PlayCallerSound(QClient.HD.PlayCallerSoundRequest request) {
            return base.Channel.PlayCallerSound(request);
        }
        
        public string PlayCallerSound(string devAddr) {
            QClient.HD.PlayCallerSoundRequest inValue = new QClient.HD.PlayCallerSoundRequest();
            inValue.Body = new QClient.HD.PlayCallerSoundRequestBody();
            inValue.Body.devAddr = devAddr;
            QClient.HD.PlayCallerSoundResponse retVal = ((QClient.HD.ControllerSoap)(this)).PlayCallerSound(inValue);
            return retVal.Body.PlayCallerSoundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.GetDeviceStatusResponse QClient.HD.ControllerSoap.GetDeviceStatus(QClient.HD.GetDeviceStatusRequest request) {
            return base.Channel.GetDeviceStatus(request);
        }
        
        public string GetDeviceStatus(int devType, string devAddr, int width, int height, int timeout) {
            QClient.HD.GetDeviceStatusRequest inValue = new QClient.HD.GetDeviceStatusRequest();
            inValue.Body = new QClient.HD.GetDeviceStatusRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.timeout = timeout;
            QClient.HD.GetDeviceStatusResponse retVal = ((QClient.HD.ControllerSoap)(this)).GetDeviceStatus(inValue);
            return retVal.Body.GetDeviceStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.GetDeviceMSGResponse QClient.HD.ControllerSoap.GetDeviceMSG(QClient.HD.GetDeviceMSGRequest request) {
            return base.Channel.GetDeviceMSG(request);
        }
        
        public string GetDeviceMSG(int devType, string devAddr, int timeout) {
            QClient.HD.GetDeviceMSGRequest inValue = new QClient.HD.GetDeviceMSGRequest();
            inValue.Body = new QClient.HD.GetDeviceMSGRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.devAddr = devAddr;
            inValue.Body.timeout = timeout;
            QClient.HD.GetDeviceMSGResponse retVal = ((QClient.HD.ControllerSoap)(this)).GetDeviceMSG(inValue);
            return retVal.Body.GetDeviceMSGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QClient.HD.InitDeviceResponse QClient.HD.ControllerSoap.InitDevice(QClient.HD.InitDeviceRequest request) {
            return base.Channel.InitDevice(request);
        }
        
        public string InitDevice(int devType, string devAddr) {
            QClient.HD.InitDeviceRequest inValue = new QClient.HD.InitDeviceRequest();
            inValue.Body = new QClient.HD.InitDeviceRequestBody();
            inValue.Body.devType = devType;
            inValue.Body.devAddr = devAddr;
            QClient.HD.InitDeviceResponse retVal = ((QClient.HD.ControllerSoap)(this)).InitDevice(inValue);
            return retVal.Body.InitDeviceResult;
        }
    }
}
