//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServeice.QueueClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ritacc.com/", ConfigurationName="QueueClient.QueueClientSoap")]
    public interface QueueClientSoap {
        
        // CODEGEN: 命名空间 http://www.ritacc.com/ 的元素名称 BussinessID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ritacc.com/BussinessQH", ReplyAction="*")]
        TestServeice.QueueClient.BussinessQHResponse BussinessQH(TestServeice.QueueClient.BussinessQHRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BussinessQHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BussinessQH", Namespace="http://www.ritacc.com/", Order=0)]
        public TestServeice.QueueClient.BussinessQHRequestBody Body;
        
        public BussinessQHRequest() {
        }
        
        public BussinessQHRequest(TestServeice.QueueClient.BussinessQHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ritacc.com/")]
    public partial class BussinessQHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BussinessID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mCard;
        
        public BussinessQHRequestBody() {
        }
        
        public BussinessQHRequestBody(string BussinessID, string mCard) {
            this.BussinessID = BussinessID;
            this.mCard = mCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BussinessQHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BussinessQHResponse", Namespace="http://www.ritacc.com/", Order=0)]
        public TestServeice.QueueClient.BussinessQHResponseBody Body;
        
        public BussinessQHResponse() {
        }
        
        public BussinessQHResponse(TestServeice.QueueClient.BussinessQHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ritacc.com/")]
    public partial class BussinessQHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BussinessQHResult;
        
        public BussinessQHResponseBody() {
        }
        
        public BussinessQHResponseBody(string BussinessQHResult) {
            this.BussinessQHResult = BussinessQHResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueueClientSoapChannel : TestServeice.QueueClient.QueueClientSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueClientSoapClient : System.ServiceModel.ClientBase<TestServeice.QueueClient.QueueClientSoap>, TestServeice.QueueClient.QueueClientSoap {
        
        public QueueClientSoapClient() {
        }
        
        public QueueClientSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueClientSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueClientSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueClientSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServeice.QueueClient.BussinessQHResponse TestServeice.QueueClient.QueueClientSoap.BussinessQH(TestServeice.QueueClient.BussinessQHRequest request) {
            return base.Channel.BussinessQH(request);
        }
        
        public string BussinessQH(string BussinessID, string mCard) {
            TestServeice.QueueClient.BussinessQHRequest inValue = new TestServeice.QueueClient.BussinessQHRequest();
            inValue.Body = new TestServeice.QueueClient.BussinessQHRequestBody();
            inValue.Body.BussinessID = BussinessID;
            inValue.Body.mCard = mCard;
            TestServeice.QueueClient.BussinessQHResponse retVal = ((TestServeice.QueueClient.QueueClientSoap)(this)).BussinessQH(inValue);
            return retVal.Body.BussinessQHResult;
        }
    }
}
